######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 19 01:14:05 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += neural.h
SOURCES += doctext.cpp neural.cpp
